### ISSUE TITLE
SPIKE: Assess suitability of list-filter module from Gov.uk

### ISSUE THREAD

**Issue by Darren-CheckPlanningData** [digital-land/lpa-data-validator-frontend#161]
Proposal:
Alex Torrance
July 16th @9:47 PM on Slack channel #providers-team-planning-data

For the organisations page we should use the list-filter module from GOV.UK as that will have been accessibility tested and it follows the same pattern.
Example: https://www.gov.uk/world
Page source: https://github.com/alphagov/collections/blob/main/app/views/world/index.html.erb
Javascript source: https://github.com/alphagov/collections/blob/main/app/assets/javascripts/modules/list-filter.js
gov.ukgov.uk
Help and services around the world - [GOV.UK](http://gov.uk/) (9 kB)
https://www.gov.uk/world

index.html.erb
[https://github.com/alphagov/collections|alphagov/collections](https://github.com/alphagov/collections%7Calphagov/collections)alphagov/collections | Added by GitHub
list-filter.js
[https://github.com/[alphagov/collections](https://github.com/alphagov/collections)|alphagov/collections](https://github.com/%5Balphagov/collections%5D(https://github.com/alphagov/collections)%7Calphagov/collections)alphagov/collections | Added by [GitHub](https://tpximpact.slack.com/services/B02K2GDF7UZ)

Questions to answer:
Will it work for our environment
Will it save time on development effort when balanced against our current technical approach

**Comment by Darren-CheckPlanningData** [comment]
Initial review suggests that this proposal will save on dev effort and will work in our environment

**Comment by GeorgeGoodall** [comment]
Questions to answer:

# Will it work for our environment
_Yes, would be worth setting up with a js bundler though_

Will it save time on development effort when balanced against our current technical approach
_Yes_
