### ISSUE TITLE
Spike: Analyse size of problem and impact for users

### ISSUE THREAD

**Issue by MJFaucherFolie** [digital-land/lpa-data-validator-frontend#184]
**Problem statement**

Having a holistic understanding of the issues we have with the data - from an internal and external user perspective, will enable us to identify common issues we can solve.

**Approach**

Identify common issues and problems people face (internal and external users)

Identify common issues and problems that occur in the data

**Acceptance criteria**

Artefacts which represent issues and problems impacting internal and external users

Links:
- [Write up of conversation with Data Management team around the problems impacting data](https://docs.google.com/document/d/1-Rpo7HMbvcdCjsyNPNuIYdPCumpwwhRwFVnBYN2PjRI/edit#heading=h.xbpl3n72owjp)
- [Draft spreadsheet investigating issues impacting data](https://docs.google.com/spreadsheets/d/1Aaw5zBUfs4rL3pRYgipkwct-Dps49qLueXCGKLh0Fyo/edit?gid=2029545334#gid=2029545334)

**Comment by Darren-CheckPlanningData** [comment]
Deprioritised work as this process will come out through user testing

**Comment by Darren-CheckPlanningData** [comment]
Deprioritised work as this process will come out through user testing
