### ISSUE TITLE
Spike: Filtering Jira tickets to help measure OKRs

### ISSUE THREAD

**Issue by MJFaucherFolie** [digital-land/lpa-data-validator-frontend#188]
**Problem statement**

One of the OKRs we will be measured by is: Support queries (over email) related to checking and providing data are reduced by 10%.

To understand if we are achieving this, we need to review Jira tickets and segment accurate data to help determine if we are achieving this.

**Approach**

Review Jira tickets and identify a way to segment them

**Acceptance criteria**

Process to segment Jira Tickets which feature back and forth support conversation, and Jira Tickets which proceed through without any support conversations.

Links:
- [Q2 Metrics for Support Queries](https://docs.google.com/spreadsheets/d/1j1r4LPq0G0TNjkV6OPGv9_NV4DPDKwOyOhKcBasgCHA/edit?gid=2029545334#gid=2029545334)

**Comment by Darren-CheckPlanningData** [comment]
Changing OKRs has made this work obsolete

**Comment by Darren-CheckPlanningData** [comment]
Changing OKRs has made this work obsolete
