### ISSUE TITLE
Service start page

### ISSUE THREAD

**Issue by CharliePatterson** [digital-land/lpa-data-validator-frontend#195]
## What

A page explaining what the service is for

## Problem statement

LPAs need to know what the service is for and what they can do

## Acceptance criteria

- [ ] User clicks on a link on the page and is taken to the page described in the link display text
- [ ] Clicking on 'Start' takes the user to the LPA finder page
- [ ] Content of the page matches the content of the prototype page

## Known Artefacts
 Link to data specifications page that the design illustrates: https://www.planning.data.gov.uk/guidance/specifications/

### Current Design

![Image](https://github.com/user-attachments/assets/9045c360-44b5-4ae3-aa94-fd76f2084ad6)

https://design-sprint-prototype-8e5ca5d98540.herokuapp.com/overview/v2/start

## Linked Tasks

**Comment by rosado** [comment]
@alextea what about the title in the header? The design doesn't have it (only on this page? on all of them?), but it's in our templates

![Image](https://github.com/user-attachments/assets/854acb6e-e43f-4e66-b040-2f76576e051b)

**Comment by alextea** [comment]
The start page template shouldn't have it, but every other page should

**Comment by rosado** [comment]
As per discussion on Slack, this should appear under `/manage`
