### ISSUE TITLE
Step-by-step page: Content & design review updates

### ISSUE THREAD

**Issue by Darren-CheckPlanningData** [digital-land/lpa-data-validator-frontend#255]
URL links on step-by-step page need updated:
Live page: https://check.planning.data.gov.uk/organisations/local-authority:LBH/brownfield-site/get-started

Tasks

- [x] Needs breadcrumb navigation
- [x] Links to the check service point to the staging env (these should be relative links)
- [x] Links to the submit service point to staging env (these should be relative links)
- [x] in '5 Update your data' > instances of 'endpoint URL' in the text, should be  'data URL'

Linked artefacts
**3. Step-by-step page**    in document: https://docs.google.com/document/d/1TtjV-czHcMmXD0qNzej8XvEP_4afov0Tb-3n7p5RpAA/edit

**Comment by GeorgeGoodall** [comment]
I'm going to tackle all the breadcrumb's across all pages in one PR
