### ISSUE TITLE
Spike: What is needed to make the Brown Field Land checker work and be integrated into the check service

### ISSUE THREAD

**Issue by Darren-CheckPlanningData** [digital-land/lpa-data-validator-frontend#289]
### Question:
What do we need to be able to check brownfield land data on the check tool?

### Answer:
- [ ]  update check to have it look for geoX and geoY in the column field log, should do this after first looking for the geometry and point column
- [ ] either construct a point from these fields and pass into the map, or update the map code to allow for geoX/geoY
- [ ] Do we need the mandatory fields for brownfield land, if so get infa to add them in (@CharliePatterson )
- [ ] add brownfield land as an option on the dataset selection page of the check

**Comment by GeorgeGoodall** [comment]
@Darren-CheckPlanningData @CharliePatterson 
this is done now, we should consider the above tasks for the next sprint
